version: "3.8"
services:
  cybercourse-container:
    container_name: cybercourse
    build: 
      context: .
      dockerfile: ./dockerfile
    ports:
      - "${NODE_PORT1}:3000"
      - "${NODE_PORT2}:3300"
    networks:
      - blog-network
    environment:
      - NODE_OPTIONS=--max_old_space_size=8000
    env_file: .env
    volumes:
      - .:/usr/src/app
  mysql-container:
    container_name: container-db-blog
    image: mysql:8.1.0
    ports:
      - 3306:20057
    networks:
      - blog-network
    environment:
      MSQL_OPTS: --skip-host-cache
    env_file: .env
    volumes:
      - Blog-data:/var/lib/mysql
volumes:
  Blog-data:
networks:
  blog-network: