version: "3.8"
services:
  my-app:
    container_name: express-container-1
    build: .
    ports:
      - "3000:3000"
    networks:
      - blog-network
    environment:
      - NODE_OPTIONS=--max_old_space_size=8000
    env_file: .env
  mysql-container:
    container_name: mysql-container-1
    image: mysql:8.1.0
    ports:
      - 20057:3306
    networks:
      - blog-network
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
networks:
  blog-network: